// Source-aware fictional press scenes: real faces, complete context, one response.
window.HL=window.HL||{};
HL.InterviewUI=(function(){
 const U=HL.UI,I=HL.Interviews,esc=U.esc;
 function panel(L){const mine=I.threads(L).filter(t=>L.career?t.source.pid===L.career.pid:t.source.teamId===L.userTeamId).slice(-8).reverse();return `<section class="block interview-room"><header><h3>Interviews & context</h3>${L.career?'':'<button class="btn small ml-auto" data-press-room>Hold a press conference</button>'}</header><div class="body">${mine.length?mine.map(t=>{const p=L.players[t.source.pid],faces=p.real?U.face(p,80,L.teams[t.source.teamId]):'',choices=t.status==='open'&&p.teamId===L.userTeamId&&!p.retired;return `<article class="interview-thread"><div class="row">${faces}<div><span class="caps">${HL.fmtDay(t.source.season,t.source.day)} · ${t.format==='clip'?'QUOTE CLIP':'INTERVIEW EXCERPT'}</span><h3>${esc(p.name)}</h3></div><span class="interview-status ml-auto">${t.status==='watching'?`${t.games}/3 team games`:esc(t.status)}</span></div><blockquote>“${esc(t.excerpt)}”<small>Selected words; the framing omits the rest of the answer.</small></blockquote><button class="btn small" data-interview-source="${t.id}">Read the full statement →</button>${choices?`<div class="career-actions interview-choices"><button data-interview-response="context" data-thread="${t.id}"><strong>Publish the context</strong><span>Show your complete answer.</span></button><button data-interview-response="wait" data-thread="${t.id}"><strong>Let the games speak</strong><span>Track three team games after the statement.</span></button><button data-interview-response="confront" data-thread="${t.id}"><strong>Challenge the framing</strong><span>Push back publicly; the argument can cost trust.</span></button></div>`:`<p class="t2 sm">${t.status==='resolved'?`${t.appearances} appearances across ${t.games} actual team games. Read the coverage below for the factual assessment.`:t.status==='cancelled'?esc(t.cancellation):'Your response is recorded. The first three team games after the statement add context.'}</p>`}</article>`;}).join(''):'<p class="t3">Public statements retain their source here. Selective excerpts can create a response scene.</p>'}<p class="t3 sm">These are fictional press scenes in this save. Real player photos support the scene; no real-world interview footage is presented as this event.</p></div></section>`;}
 function bind(root,L,changed){const save=async()=>{await HL.Saves.save(L);changed();};
  root.querySelectorAll('[data-interview-source]').forEach(b=>b.onclick=()=>{const t=I.threads(L).find(t=>t.id===+b.dataset.interviewSource),p=L.players[t.source.pid];U.sheet(`<h3>${esc(p.name)} · Full statement</h3>`,`<div class="interview-source"><span class="caps">In-save press conference · ${HL.fmtDay(t.source.season,t.source.day)}</span><h3>What was said</h3><blockquote>“${esc(t.source.fullQuote)}”</blockquote><h3>What circulated</h3><blockquote>“${esc(t.excerpt)}”</blockquote><p>The excerpt uses recorded words. Its framing omits the complete answer; this source remains unchanged by your response.</p></div>`,{width:640});});
  root.querySelectorAll('[data-interview-response]').forEach(b=>b.onclick=async()=>{const r=I.respond(L,+b.dataset.thread,b.dataset.interviewResponse);if(!r.ok)return U.toast(esc(r.reason));await save();HL.FX.sfx.land();});
  root.querySelector('[data-press-room]')?.addEventListener('click',()=>{const players=HL.League.teamPlayers(L.userTeamId).filter(p=>!p.retired);const m=U.sheet('<h3>In-save press conference</h3>',`<label>Speaker<select data-press-speaker>${players.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Your answer<textarea data-press-words rows="4" maxlength="2000" placeholder="Write the complete words you want the player to say. Leave blank to draft a scene-aware answer."></textarea></label><label>Answer approach<select data-press-tone><option value="custom">Your own words</option><option value="humble">Humble · keep working</option><option value="confident">Confident · big moments, team first</option><option value="deflect">Deflect · keep the next step private</option></select></label><button class="btn go" data-press-confirm>Give this answer</button><p data-press-result role="status"></p>`,{width:560});m.querySelector('[data-press-confirm]').onclick=async()=>{const r=I.hold(L,+m.querySelector('[data-press-speaker]').value,m.querySelector('[data-press-tone]').value,m.querySelector('[data-press-words]').value);m.querySelector('[data-press-result]').textContent=r.ok?r.source.fullQuote:r.reason;if(r.ok){await save();m.querySelector('[data-press-confirm]').textContent='Answer another question';}};});
 }
 return {panel,bind};
})();
