window.HL=window.HL||{};
HL.PlayerPostUI=(function(){
 const U=HL.UI,P=HL.PlayerPosts,esc=U.esc;
 function panel(L){const posts=P.entries(L).slice(-8).reverse(),available=P.available(L);return `<section class="block player-post-room"><header><h3>${L.season>=2010?'Player voices':'Public statements'}</h3>${available.length?'<button class="btn small ml-auto" data-post-compose>Make a statement</button>':''}</header><div class="body"><div class="player-post-grid">${posts.map(post=>{const p=L.players[post.pid],canReply=!post.reply&&p&&!p.retired&&(!L.career||p.id!==L.career.pid);return `<article class="player-post-card"><header>${p?.real?U.face({...p,name:post.name,number:post.number},44,post.team,post.season):''}<div><b>${esc(post.name)}</b><small>${esc(post.team.city)} ${esc(post.team.name)} · ${HL.fmtDay(post.season,post.day)}</small></div><span class="tag ml-auto">${post.format==='social'?'PLAYER POST':'PUBLIC WORDS'}</span></header>${p?.real?`<div class="player-post-photo">${HL.GFX.figure({...p,name:post.name,number:post.number},post.team,{season:post.season})}<span class="player-post-photo-label">Archive portrait · in-save statement</span></div>`:`<div class="player-post-created"><b>${esc(post.name)}</b><span>#${post.number} · Your public voice</span></div>`}<div class="player-post-copy"><blockquote>“${esc(post.caption)}”</blockquote>${post.format==='social'?`<p class="t3 sm">${post.likes.toLocaleString()} reactions</p>`:''}<span class="caps">${post.status==='watching'?'The named matchup is still ahead':post.status==='cancelled'?esc(post.cancellation):post.status==='resolved'?`${post.outcome.min>0?post.outcome.pts+' actual points':'Did not play'} · Team ${post.outcome.won?'win':'loss'} ${esc(post.outcome.score)}`:''}</span><div class="player-post-comments">${post.comments.map(c=>`<p><b>${esc(c.speaker)}</b> ${esc(c.text)}</p>`).join('')}${post.reply?`<p><b>${esc(post.reply.author)}</b> ${esc(post.reply.text)}</p>`:''}</div>${canReply?`<div class="row wrap"><button class="btn small" data-post-reply="support" data-post="${post.id}">Support</button>${post.facts.won&&post.facts.min>0?`<button class="btn small" data-post-reply="congratulate" data-post="${post.id}">Give credit</button>`:''}<button class="btn small quiet" data-post-reply="challenge" data-post="${post.id}">Challenge</button></div>`:''}</div></article>`;}).join('')||'<p class="t3">Players speak after standout actual performances. Your public choices start a thread here.</p>'}</div><p class="t3 sm">From your saved timeline · Archive portraits support fictional player statements. One public reply per day.</p></div></section>`;}
 function bind(root,L,changed){const save=async()=>{await HL.Saves.save(L);changed();};
  root.querySelector('[data-post-compose]')?.addEventListener('click',()=>{const available=P.available(L),m=U.sheet(`<h3>${L.season>=2010?'Your public voice':'Public statement'}</h3>`,`<label>Speaker<select data-post-speaker>${available.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label><label>Topic<select data-post-topic>${Object.entries(P.topics).map(([key,label])=>`<option value="${key}">${esc(label)}</option>`).join('')}</select></label><p class="t3">One statement per player every seven calendar days. A challenge names the next actual matchup; a celebration needs a recent team win.</p><button class="btn go" data-post-confirm>Publish this statement</button><p data-post-result role="status"></p>`,{width:560});m.querySelector('[data-post-confirm]').onclick=async()=>{const r=P.post(L,+m.querySelector('[data-post-speaker]').value,m.querySelector('[data-post-topic]').value);m.querySelector('[data-post-result]').textContent=r.ok?r.post.caption:r.reason;if(r.ok){m.querySelector('[data-post-confirm]').disabled=true;await save();HL.FX.sfx.land();}};});
  root.querySelectorAll('[data-post-reply]').forEach(b=>b.onclick=async()=>{const r=P.reply(L,+b.dataset.post,b.dataset.postReply);if(!r.ok)return U.toast(esc(r.reason));await save();U.toast(esc(r.response));});
 }
 return {panel,bind};
})();
