// Saved, context-aware dialogue. Never draws from the possession simulator's RNG.
window.HL=window.HL||{};
HL.PublicVoices=(function(){
 function pick(L,key,lines){const d=L.publicVoices||(L.publicVoices={used:{},seq:0}),used=d.used[key]||[],pool=lines.filter(x=>!used.includes(x)),eligible=pool.length?pool:lines;let hash=0;for(const c of key)hash=(hash*31+c.charCodeAt(0))>>>0;const text=eligible[(hash+d.seq++)%eligible.length];d.used[key]=[...used,text].slice(-6);const keys=Object.keys(d.used);for(const k of keys.slice(0,-400))delete d.used[k];return text;}
 function recent(L,p){return Object.entries(L.boxScores||{}).reverse().map(([gid,r])=>{const side=[r.home,r.away].find(s=>s.teamId===p.teamId);if(!side)return null;const other=side===r.home?r.away:r.home,b=side.box[p.id]||{};return {gid,day:r.day,pts:b.pts||0,min:b.min||0,won:side.score>other.score,score:`${side.score}–${other.score}`,oppId:other.teamId};}).find(Boolean);}
 function previous(L,pid,targetId){return (L.playerPosts?.entries||[]).slice().reverse().find(e=>e.pid===pid&&e.target?.id===targetId&&e.visibility!=='private');}
 const detail=e=>e.caption.length>70?e.caption.slice(0,67)+'…':e.caption;
 function defaults(L,p,topic,target,f){const team=L.teams[p.teamId],old=L.season<2010,name=target?.name||'you';const modern={
  team:[`Love playing for this city. ${team.name}, let's keep it going.`,`Everybody in that locker room has a part in this. Proud of our group.`,`Not about one guy. I want us to get there together.`],
  work:[`Got some things to clean up. Back in the gym tomorrow.`,`Film, practice, repeat. That's where I'm at right now.`,`Not happy with everything, but we'll work through it.`],
  challenge:[`Looking forward to that matchup. Should be a good one.`,`Got the ${L.teams[f.oppId]?.name||'next opponent'} next. Let's get to it.`,`We'll be ready. That's all I've got for now.`],
  praise:[`${name}, that was good basketball. Respect.`,`I like how ${name} plays. Makes the guys around him better.`,`Credit to ${name}. You can see the work.`],
  callout:[`${name}, let's see what happens when we line up.`,`I'm not ducking that matchup with ${name}.`,`Everybody's got a lot to say. ${name}, see you on the floor.`],
  apology:[`I could've handled that better. That's on me.`,`Didn't come out the way I meant it. I owe ${name} a conversation.`,`I said what I said, but I crossed a line. I'll own that.`],
  recruit:[`${name}, we'd be fun to watch together. Just saying.`,`I'd love to share the floor with ${name} someday.`,`Imagine what ${name} could do with this group.`],
  trade:[`I've told the club how I feel. I'm ready for a fresh start.`,`I need a real conversation about my future here.`,`This isn't working the way I hoped. My agent and I are talking to the team.`],
  role:[`I want more responsibility. I'll have that conversation with the coach.`,`I feel like I can help more than I'm being asked to right now.`,`I'm ready for a bigger role. I want a chance to show it.`],
  coach:[`We need to talk about how we're using this group.`,`Some of the decisions haven't made sense to me. I'd rather talk it through than pretend.`,`We've got to be clearer about what we're trying to do.`],
  rules:[`I don't agree with the way that rule works. Players should have a say.`,`We've got to talk about that rule. It changes how you can play.`,`I'm asking the league to explain this one.`],
  message:[`${name}, can we talk away from all this?`,`Wanted to check in with you, ${name}. How are you doing?`,`I'd rather tell you directly than put it out there.`],
  custom:[`Been thinking about this season. A lot left to do.`,`Appreciate everybody who's been showing up for us.`,`Long day. Looking forward to being back out there.`]
 };if(old)return pick(L,`default:${p.id}:${topic}`,topic==='challenge'?[`I look forward to our next contest.`,`We expect a hard match and intend to be ready.`]:topic==='work'?[`There are parts of my game I intend to improve.`,`Practice will be my chief concern this week.`]:[`I would like to speak plainly about ${target?target.name:'our team'}.`,`I am grateful for the opportunity to represent the ${team.name}.`]);return pick(L,`default:${p.id}:${topic}`,modern[topic]||modern.custom);}
 function comments(L,p,e,prior){const old=L.season<2010,t=e.target&&L.players[e.target.id],r=t&&HL.World?.relationship(L,t.id),game=recent(L,p),team=L.teams[e.teamId],q=detail(e),out=[],key=role=>`${role}:${p.id}:${t?.id||0}:${e.topic}`;const add=(speaker,role,lines,context,extra={})=>out.push({speaker,role,text:pick(L,key(role),lines),context,...extra});
  if(e.visibility==='private'){
   const distrust=(r?.trust??50)<35,previous=prior?.topic==='callout'||prior?.topic==='fabricate';add(t.name,'person',old?[`I have received your message. We should discuss it in person.`]:distrust||previous?[`You put me on blast and now you want to talk privately? Explain that first.`,`I'm listening. But we need to deal with what you said before.`]:[`Yeah, call me after practice.`,`Appreciate you reaching out. What's on your mind?`,`Let's talk. I'd rather do it this way too.`],`private message; trust ${r?.trust??50}; prior ${prior?.topic||'none'}`,{pid:t.id,delivery:'private'});return out;
  }
  if(t&&['praise','callout','apology','recruit','fabricate'].includes(e.topic)){
   let lines,context=`${e.topic}; trust ${r?.trust??50}; ego ${t.traits?.ego??50}; prior ${prior?.topic||'none'}`;
   if(e.topic==='praise')lines=old?[`I thank ${p.name} for his generous remarks.`]:[`Appreciate you, ${p.name.split(' ')[0]}.`,`Respect. We've both been putting in the work.`,`That's love. Looking forward to playing you again.`];
   if(e.topic==='callout')lines=old?[`The next contest will provide a better answer than this exchange.`]:(t.traits?.ego??50)>=70?[`You want to make it personal, ${p.name.split(' ')[0]}? We can do that.`,`Keep that same energy when we're on the floor.`,`You've said your piece. Don't walk it back at tipoff.`]:[`I'm not doing the back-and-forth. See you at the game.`,`He can say what he wants. I've got a team to worry about.`,`What exactly are we arguing about here?`];
   if(e.topic==='apology')lines=old?[`I will discuss the matter with him privately.`]:(r?.trust??50)<35?[`I hear you. It doesn't fix everything in one conversation.`,`An apology is a start. Show me you mean it.`]:[`We're good. Let's talk without everyone watching.`,`Appreciate you saying that. We can move on.`];
   if(e.topic==='recruit')lines=old?[`My obligations are with my present club. No agreement has been made.`]:prior?.topic==='callout'?[`You just called me out. Now you want me on your team?`,`Let's sort out what you said about me before talking about teaming up.`]:(r?.trust??50)<35?[`I haven't forgotten how you've handled things. I'm not making plans with you.`,`That's a conversation for another time. I've got a team.`]:[`That would be interesting. I'm with the ${L.teams[t.teamId]?.name||'club'} right now, though.`,`Ha. You know I can't answer that here.`,`We've talked hoops before. Doesn't mean there's a deal.`];
   if(e.topic==='fabricate')lines=old?[`I dispute the quotation attributed to me and request the original record.`]:[`Where did you get that quote? Show the whole interview.`,`I didn't give you those words. Put the source up.`,`Don't put words in my mouth, ${p.name.split(' ')[0]}.`];
   add(t.name,'person',lines,context,{pid:t.id,delivery:e.channel==='press'?'interview':'reply'});
  }
  if(['clip','context'].includes(e.topic)){
   const src=e.source,leak=src.visibility==='private',full=src.fullQuote;
   add(old?'Sports editor':'Local beat reporter','reporter',e.topic==='context'?[`The full answer is available: “${full}”. Readers can compare it with the excerpt.`]:leak?[`${src.name}'s private message has been published. The original says “${full}”. The leak itself is now part of the story.`]:[`The selected words are “${e.excerpt}”. ${src.name}'s full answer also says: “${full}”.`,`That excerpt is from a longer statement by ${src.name}. Here are the original words: “${full}”.`],`recorded source ${src.key}; ${leak?'private leak':'public record'}`);
   add(old?'Reader correspondence':'Reply to the clip','fan',old?[`The complete remarks deserve consideration.`]:e.topic==='context'?[`That second sentence changes the whole thing.`,`Why wasn't the rest of the answer in the first post?`]:[`Put the whole answer up. This edit leaves something out.`,`I'm reading the source before buying that caption.`],`source comparison`);return out;
  }
  const last=game?game.min>0?`${game.pts} points in a ${game.score} ${game.won?'win':'loss'}`:`a ${game.score} ${game.won?'win':'loss'} while he didn't play`:null;
  if(['trade','role','coach','recruit','rules','guarantee','winpromise','fabricate'].includes(e.topic)){
   const angle=e.topic==='trade'?`${p.name} is asking for a move; ${team.name} still control his current contract.`:e.topic==='role'?`${p.name} wants a larger role${game?`; his latest team game gave him ${game.min.toFixed(1)} minutes`:''}. No rotation change has been announced.`:e.topic==='recruit'?`${p.name} publicly mentioned playing with ${t.name}. There is no recorded agreement or roster move.`:e.topic==='guarantee'?`${p.name} has promised ${e.points} points in the scheduled game against the ${L.teams[e.targetOpp].name}.` :e.topic==='winpromise'?`${p.name} has called a win against the ${L.teams[e.targetOpp].name}. The result is still ahead.`:e.topic==='fabricate'?`The words attributed to ${t.name} have no recorded source in this save. The claim is unverified.`:e.topic==='rules'?`${p.name} objects to the rules: “${q}”. A public objection does not itself change league policy.`:`${p.name} has questioned the coaching: “${q}”. The club has not announced a staff change.`;
   add(old?'Basketball correspondent':'Team beat reporter','reporter',[angle],`intent ${e.topic}; ${last||'no prior game'}; no inferred transaction`);
  }
  const fanLines=old?[`${team.city} supporters will follow this matter with interest${last?` after ${last}`:''}.`]:e.topic==='callout'?[`${t.name.split(' ').at(-1)} is going to remember “${q}”.`,`Okay, now that matchup has something extra on it. ${t.name.split(' ').at(-1)} heard you.`]:e.topic==='recruit'?[`No deal, but ${t.name.split(' ').at(-1)} with this group would be wild.`,`His current team's fans aren't going to love that.`]:e.topic==='fabricate'?[`Where's the clip? I'm not believing “${q}” without it.`,`That's a pretty big claim. Someone better have a source.`]:e.topic==='apology'?[`Own it and move on. Don't turn the apology into another argument.`,`Hope they actually talk instead of doing this in the replies.`]:e.topic==='trade'?[`Asking out of ${team.name} is a big step. What's broken here?`,`We've been rooting for him. I want to hear the club's side too.`]:e.topic==='celebrate'?[`Enjoy that one. ${L.teams[e.facts.oppId].name} made you work for it.`,`That's our group. Good win.`]:last?[`After ${last}, I can see why people are listening.`,`“${q}” — curious what he means by that after the last game.`]:[`“${q}” — that's what he actually said. Don't add a whole story to it.`,`Not every post needs to become a controversy.`,`Let him talk. The season's long.`];
  add(old?`${team.city} supporters`:`${team.abbr} fan replies`,'fan',fanLines,`${e.topic}; ${last||'no actual appearance to cite'}`);return out;
 }
 function answer(L,speaker,e,choice,text){const prior=e.replies?.at(-1)||e.reply,r=HL.World?.relationship(L,speaker.id),name=speaker.name.split(' ')[0],old=L.season<2010;let lines;
  if(old)lines=choice==='challenge'?[`I understand the objection. The next contest will have to settle it.`,`I would prefer that the complete remarks be considered.`]:[`I appreciate the reply. I shall consider what you have said.`,`Thank you. We can discuss this more fully in person.`];
  else if(e.topic==='fabricate')lines=[`The question is still the source. Where is it?`,`Answer that first: who recorded those words?`];
  else if(e.topic==='clip')lines=[`The whole answer is right there. Why leave the rest out?`,`You can disagree. Don't change what the source actually says.`];
  else if(prior&&choice==='challenge')lines=[`You said “${text.slice(0,80)}”. What part of my answer are you disagreeing with?`,`We've been over this. If you mean “${text.slice(0,80)}”, say that directly.`,`I'd rather talk this through than keep arguing in a thread.`];
  else if(prior&&e.visibility==='private')lines=[`Good to hear from you again. We can keep this between us.`,`I'm glad we could talk directly. Tell me what's on your mind.`,`Yeah, I hear you. It's easier without everybody weighing in.`];
  else if(choice==='congratulate')lines=[`Appreciate it. Guys around me made that one happen.`,`Thank you. Good to get that one for the team.`];
  else if(choice==='challenge')lines=(r?.trust??50)<35?[`You keep questioning me. We need a real conversation.`,`I'm not taking that from someone who hasn't backed me.`]:(speaker.traits?.ego??50)>=70?[`You talking to me, or talking for the cameras?`,`Say it to me when we're in the same room.`]:[`Fair question. We'll see how it goes.`,`I hear you. I'm not going to argue about it here.`];
  else lines=[`Appreciate you reaching out.`,`I hear what you're saying about “${text.slice(0,60)}”.`,`Thanks. I'd rather talk basketball than get into all of this.`];
  return {text:pick(L,`answer:${speaker.id}:${e.topic}:${choice}`,lines),context:`${name}; trust ${r?.trust??50}; ${prior?'continuing conversation':'first response'}; topic ${e.topic}`};
 }
 function performance(L,p,f){const old=L.season<2010,opp=L.teams[f.oppId].name,game=recent(L,p),previous=game&&game.gid!==f.gid;const lines=old?f.won?[`A fine team effort against the ${opp}.`,`I am pleased we were able to win this contest.`]:[`The ${opp} deserved the result. We have work to do.`,`A disappointing result, whatever my own figures may show.`]:f.won?[`Good one tonight. Love this group.`,`That was fun. Appreciate our fans showing up.`,`Big plays from everybody. Good win.`,`Kept our heads when it got tight. Proud of that.`,`Respect to the ${opp}. We needed that one.`,`Home safe. Film tomorrow.`,`All that work together showed up tonight.`,`Glad we got that one for the city.`,...(previous&&!game.won?[`Needed a response after last game. That's a start.`]:[])]:[`Not the result we came for. Credit to the ${opp}.`,`Tough one. I've got to be better in the next game.`,`No excuses. Watch it back and get ready for the next one.`,`Can't enjoy the numbers when we lose.`,`We'll stick together. Back at it tomorrow.`,`The ${opp} made the plays. We've got to answer that.`];return pick(L,`performance:${p.id}:${f.won}`,lines);}
 function headline(L,p,e){const name=p.name,t=e.target?.name,club=e.team.name;return ({praise:`${name} gives ${t} credit`,callout:`${name} takes aim at ${t}`,apology:`${name} apologizes to ${t}`,recruit:`${name} floats teaming up with ${t}`,trade:`${name} asks for a fresh start away from ${club}`,role:`${name} pushes for a bigger role with ${club}`,coach:`${name} questions the coaching in ${e.team.city}`,rules:`${name} challenges the league over its rules`,guarantee:`${name} calls ${e.points} points against the ${L.teams[e.targetOpp]?.name}`,winpromise:`${name} guarantees a win over the ${L.teams[e.targetOpp]?.name}`,fabricate:`Unsourced quote attributed to ${t} draws a dispute`,clip:`${e.source?.name}'s words circulate in a selected excerpt`,context:`${name} publishes the full answer behind the excerpt`,performance:`${name} reacts to ${e.facts.won?'beating':'losing to'} the ${L.teams[e.facts.oppId]?.name}`,celebrate:`${name} celebrates the ${club} win`})[e.topic]||`${name}: “${e.caption.slice(0,90)}${e.caption.length>90?'…':''}”`;}
 function presser(L,p,tone,scene){const old=L.season<2010,played=scene.min>0,claim=tone==='confident'?'I will score at least 20 in our next game. Hold me to it.':null;if(claim)return claim;
  const lines=old?tone==='humble'?[`I have much to improve. I intend to apply myself in practice.`,`The credit belongs to the team. There is work ahead.`]:[`I prefer to discuss the team's performance. My personal plans remain private.`]:tone==='humble'?played?[`I left a few plays out there. I'll watch it back and work on those.`,`Happy to help, but I can do a lot better. I've got to keep putting the work in.`,`The guys made my job easier tonight. I'm still figuring some things out.`]:[`I didn't get on the floor tonight. All I can do is stay ready and keep working.`,`No minutes for me tonight. I'm going to talk to the coach about what he needs.`]:[`I'm not going to get into my next step here. Ask me about the game.`,`That's between me and the team. Tonight was about what our group did.`,`We'll talk about the future when it's time. Right now I'm focused on this locker room.`];return pick(L,`presser:${p.id}:${tone}:${played}`,lines);}
 return {pick,recent,previous,defaults,comments,answer,performance,headline,presser};
})();
