"""Builds data/nbaids.js (player name -> NBA.com personId) from the nba_api package's static player index.
Usage: python3 tools/build-nbaids.py path/to/nba_ids.json
(nba_ids.json = [[id, full_name, is_active], ...] extracted from nba_api/stats/library/data.py)"""
import json, sys, unicodedata
src = json.load(open(sys.argv[1]))
def norm(n):
    n = unicodedata.normalize('NFKD', n).encode('ascii', 'ignore').decode().lower()
    return ''.join(c for c in n if c.isalnum())
out = {}
for pid, name, active in src:
    k = norm(name)
    # Prefer active players when two share a name.
    if k not in out or active:
        out[k] = pid
with open('data/nbaids.js', 'w') as f:
    f.write('// name (normalized) -> NBA.com personId, used for real headshots. Generated by tools/build-nbaids.py\n')
    f.write('window.HL = window.HL || {};\nHL.NBA_IDS = ' + json.dumps(out, separators=(',', ':')) + ';\n')
print(len(out), 'ids')
