// Builds docs/scenarios/LEDGER.md: every proposed scenario (scenarios-1.json), Claude's additions,
// and the original media catalog, with implementation status, handler and evidence.
// Usage: node tools/scenario-ledger.js
const fs = require('fs');
const path = require('path');
const dir = path.join(__dirname, '../docs/scenarios');
const reg = JSON.parse(fs.readFileSync(path.join(dir, 'scenarios-1.json'), 'utf8'));
const status = JSON.parse(fs.readFileSync(path.join(dir, 'status.json'), 'utf8'));
const extra = JSON.parse(fs.readFileSync(path.join(dir, 'claude-additions.json'), 'utf8'));

// Original catalog keys = modern keys in media packs 1 and 3; "wired" = the game code emits that key.
const { load, ctx } = require('./load');
load(['packs/media-pack-1.js', 'packs/media-pack-3.js']);
const catalog = new Set();
for (const pk of ctx.HL_PACKS || []) for (const k of Object.keys(pk.lines)) if (!k.includes('@')) catalog.add(k);
const code = [];
const walk = d => { for (const f of fs.readdirSync(d)) { const p = path.join(d, f); if (fs.statSync(p).isDirectory()) walk(p); else if (f.endsWith('.js')) code.push(fs.readFileSync(p, 'utf8')); } };
walk(path.join(__dirname, '../js'));
const src = code.join('\n');
const wired = k => src.includes(`'${k}'`) || src.includes(`"${k}"`) || src.includes('`' + k);

const ORDER = ['implemented', 'partial', 'blocked', 'not started'];
const st = k => (status[k] && status[k].status) || 'not started';
const count = list => Object.fromEntries(ORDER.map(s => [s, list.filter(x => x === s).length]));
const all = reg.scenarios.map(s => st(s.key));
const c = count(all);
const esc = s => String(s || '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

let md = `# Scenario ledger\n\nGenerated by \`node tools/scenario-ledger.js\` from \`scenarios-1.json\` (proposed by the content handoff), \`claude-additions.json\` and \`status.json\`.\nA scenario counts as implemented only when the game simulates its trigger and consequences, not when a headline exists.\n\n`;
md += `## Summary\n\n| | Implemented | Partial | Blocked | Not started | Total |\n|---|---|---|---|---|---|\n`;
md += `| Proposed scenarios | ${c.implemented} | ${c.partial} | ${c.blocked} | ${c['not started']} | ${all.length} |\n`;
const ex = count(extra.scenarios.map(s => s.status));
md += `| Claude additions | ${ex.implemented} | ${ex.partial} | ${ex.blocked} | ${ex['not started']} | ${extra.scenarios.length} |\n`;
const cat = [...catalog].sort();
const cw = cat.filter(wired).length;
md += `| Original media catalog (emitted by the game) | ${cw} | | | ${cat.length - cw} | ${cat.length} |\n\n`;

md += `## Claude additions\n\n| Key | Status | Trigger | Handler | Evidence |\n|---|---|---|---|---|\n`;
for (const s of extra.scenarios) md += `| \`${s.key}\` | ${s.status} | ${esc(s.trigger)} | ${esc(s.handler)} | ${esc(s.evidence)} |\n`;

md += `\n## Original media catalog\n\nEmitted now: ${cat.filter(wired).map(k => `\`${k}\``).join(', ')}.\n\nWaiting on features: ${cat.filter(k => !wired(k)).map(k => `\`${k}\``).join(', ')}.\n`;

md += `\n## Proposed scenarios by category\n`;
const cats = [...new Set(reg.scenarios.map(s => s.category))];
for (const cname of cats) {
  const list = reg.scenarios.filter(s => s.category === cname);
  const cc = count(list.map(s => st(s.key)));
  md += `\n### ${cname}\n\n${ORDER.filter(s => cc[s]).map(s => `${cc[s]} ${s}`).join(' · ')}\n\n`;
  const touched = list.filter(s => status[s.key]);
  if (touched.length) {
    md += `| Key | Status | Handler / data | Evidence / note |\n|---|---|---|---|\n`;
    for (const s of touched) { const x = status[s.key]; md += `| \`${s.key}\` | ${x.status} | ${esc([x.handler, x.data].filter(Boolean).join('; '))} | ${esc([x.evidence, x.note].filter(Boolean).join(' '))} |\n`; }
    md += '\n';
  }
  const rest = list.filter(s => !status[s.key]);
  if (rest.length) md += `Not started: ${rest.map(s => `\`${s.key}\``).join(', ')}\n`;
}
fs.writeFileSync(path.join(dir, 'LEDGER.md'), md);
console.log(`LEDGER.md: proposed ${JSON.stringify(c)}; additions ${extra.scenarios.length}; catalog emitted ${cw}/${cat.length}`);
