// Player Career creator and a player-owned hub: decisions, basketball and a remembered life.
window.HL=window.HL||{};
HL.CareerUI=(function(){
 const U=HL.UI,C=HL.Career,esc=U.esc,L=()=>HL.League.get(),p=()=>L().players[L().career.pid];let tab='today',busy=false;
 const tabs=[['today','Today'],['basketball','Basketball'],['people','People'],['life','Life'],['media','Media'],['story','Story']];
 const money=n=>'$'+Math.round(n).toLocaleString();
 const meter=(name,value)=>`<div class="meter"><span class="lbl">${name}</span><span class="val">${value}</span><div class="track"><i style="width:${value}%"></i></div></div>`;
 async function save(){try{await HL.Saves.save(L());}catch(e){U.toast(`Could not save: ${esc(e.message)}`);}}
 function setup(){
  const config={...C.defaults,seed:Math.floor(Math.random()*1e8)},seasons=HL.HISTORY.seasons.filter(k=>!k.includes('-')).map(Number).sort((a,b)=>b-a);U.setEra('modern');U.applyTeamTheme(null);
  const input=(key,label,min,max)=>`<label>${label}<input data-create="${key}" type="${min==null?'text':'number'}" ${min==null?'maxlength="60"':`min="${min}" max="${max}"`} value="${esc(String(config[key]))}"></label>`;
  const select=(key,label,options)=>`<label>${label}<select data-create="${key}">${options.map(([v,label])=>`<option value="${v}" ${String(v)===String(config[key])?'selected':''}>${label}</option>`).join('')}</select></label>`;
  U.app().innerHTML=`<div class="frame"><div class="masthead"><div class="bar"><div class="wordmark" data-career-home>Hoops<i>Life</i></div><h3>Player Career</h3></div></div><main class="page"><div class="page-title"><h2>Create your prospect</h2><span class="t2">A body, a playing style, a life. Ability is earned.</span></div><div class="career-creator"><div class="stack"><section class="block"><header><h3>Identity & entry</h3></header><div class="body career-fields">${input('name','Name')}${input('hometown','Hometown')}${input('nationality','Nationality')}${select('season','Debut season',seasons.map(y=>[y,`${y}–${String(y+1).slice(2)}`]))}${select('age','Age',[[19,19],[20,20],[21,21],[22,22]])}${select('route','Background',[['college','College prospect'],['international','International prospect']])}</div></section><section class="block"><header><h3>Body & game</h3></header><div class="body career-fields">${select('pos','Position',HL.POSITIONS.map(p=>[p,p]))}${select('arch','Primary style',Object.entries(HL.ARCHETYPES).map(([key,a])=>[key,a.label]))}${select('secondary','Secondary style',Object.entries(HL.ARCHETYPES).map(([key,a])=>[key,a.label]))}${input('height','Height · inches',72,90)}${input('weight','Weight · lb',160,340)}${input('wingspan','Wingspan · inches',72,100)}${select('hand','Dominant hand',[['right','Right'],['left','Left']])}${input('number','Jersey number',0,99)}${select('personality','Personality',[['driven','Driven · work first'],['quiet','Quiet · trust and loyalty'],['showman','Showman · visibility and ego']])}</div></section></div><aside class="career-preview" data-career-preview></aside></div><p class="t3 sm">This first Career milestone begins at NBA entry. School/college play, real-player replacement and the larger life, health and business systems are still in development. Draft placement and role are simulated; you cannot set your rating or force a team.</p><div class="row wrap"><button class="btn quiet" data-career-home>Back</button><button class="btn go big ml-auto" data-career-start>Enter the league</button></div><p role="alert" data-career-create-error></p></main></div>`;
  const refresh=()=>{const r=C.preview(config),host=U.app().querySelector('[data-career-preview]');if(!r.ok){host.innerHTML=`<p class="t2">${esc(r.reason)}</p>`;return;}const q=r.player;host.innerHTML=`${HL.GFX.jerseyCard(q,null,{sub:`${q.pos} · ${HL.fmtHeight(q.height)} · ${q.weight} lb`})}<div class="career-preview-stats"><h3>Your starting tools</h3>${HL.ATTRS.slice().sort((a,b)=>q.attrs[b.key]-q.attrs[a.key]).slice(0,6).map(a=>`<div class="row"><span>${a.label}</span><b class="ml-auto">${q.attrs[a.key]}</b></div>`).join('')}<p class="t3 sm">Prospect rating ${q.ovr}. Training and performance build from here.</p></div>`;};
  U.app().querySelectorAll('[data-create]').forEach(el=>el.addEventListener('change',()=>{const key=el.dataset.create;config[key]=['age','height','weight','wingspan','number','season'].includes(key)?+el.value:el.value;refresh();}));
  U.app().querySelectorAll('[data-career-home]').forEach(b=>b.onclick=()=>HL.App.title());
  U.app().querySelector('[data-career-start]').onclick=async e=>{if(busy)return;busy=true;e.currentTarget.disabled=true;try{const check=C.preview(config);if(!check.ok)throw new Error(check.reason);await HL.History.load(String(config.season));const r=C.create(config);if(!r.ok)throw new Error(r.reason);tab='today';open();await save();HL.FX.sfx.fanfare();}catch(e){U.app().querySelector('[data-career-create-error]').textContent=e.message;}finally{busy=false;const b=U.app().querySelector('[data-career-start]');if(b)b.disabled=false;}};refresh();
 }
 function actions(group){return `<div class="career-actions">${Object.entries(C.ACTIONS).filter(([k,a])=>a.group===group).map(([key,a])=>`<button data-career-action="${key}"><strong>${a.label}</strong><span>${a.desc}</span></button>`).join('')}</div>`;}
 function lastGame(){const g=L().career.gameLog.at(-1);if(!g)return '<p class="t3">Your first team game is still ahead.</p>';const opp=L().teams[g.opponent];return `<div class="career-result"><span class="caps">${HL.fmtDay(g.season,g.day)} · ${g.playoff?'Playoffs':'Regular season'} · ${esc(opp.name)}</span><h3>${g.won?'WIN':'LOSS'} ${g.score}</h3><div class="career-statline"><div><b>${g.pts}</b>PTS</div><div><b>${g.reb}</b>REB</div><div><b>${g.ast}</b>AST</div><div><b>${g.min.toFixed(1)}</b>MIN</div></div>${g.min===0?'<p class="t2">Did not play. No personal scoring line is invented.</p>':''}</div>`;}
 function today(){const lg=L(),c=lg.career,q=p(),t=lg.teams[q.teamId??lg.userTeamId],next=lg.schedule.find(g=>!g.res&&(g.home===t.id||g.away===t.id)),offers=C.offers(lg);
  if(lg.phase==='offseason'){C.offseason(lg);return `<section class="career-game-stage"><div class="draft-kicker">OFFSEASON · YOUR NEXT CHAPTER</div><h2>Review. Decide. Return.</h2><p>The season report is in Story. Training, family and relationships continue between seasons.</p>${q.contract.exp<=lg.season&&!c.retired?'<p class="t2">Your contract has expired. Choose an offer before advancing.</p>':''}<button class="btn go big" data-career-advance>Open next season</button></section>${contractOffers(offers)}`;}
  const opp=next&&lg.teams[next.home===t.id?next.away:next.home],stars=opp&&HL.League.teamPlayers(opp.id).sort((a,b)=>b.ovr-a.ovr).slice(0,2);
  return `<div class="career-today"><section class="career-game-stage"><div class="draft-kicker">${c.retired?'LIFE AFTER THE LEAGUE':c.role.toUpperCase()+' · '+q.realMpg+' TARGET MINUTES'}</div><h2>${c.retired?'Your story continues.':next?`Next: ${esc(opp.name)}`:lg.phase==='regular'?'The season moves on.':'The postseason is live.'}</h2><p>${c.retired?'Family, finances and your legacy remain in this save. A comeback needs an actual contract.':next?`${HL.fmtDay(lg.season,next.day,{weekday:true})} · ${esc(t.name)} ${t.w}–${t.l} · ${q.injury?`Injury: ${esc(q.injury.name)}, ${q.injury.games} team games remaining.`:'Prepare, choose your approach, then let the simulation decide.'}`:'Keep following the league and your actual playoff path.'}</p>${stars?`<div class="career-opponents">${stars.map(q=>`<div>${U.face(q,64,opp)}<span>${esc(q.name)}</span></div>`).join('')}</div>`:''}<div class="row wrap">${lg.phase==='regular'&&!c.retired&&q.teamId!=null?'<button class="btn big" data-live-start>Enter live game →</button>':''}<button class="btn go big" data-career-next>${c.retired?'Advance one week':'Sim next team game'}</button><button class="btn" data-career-week>One week</button><button class="btn quiet" data-career-season>Finish season</button></div>${c.pendingPress?'<button class="btn small" data-career-jump="media">Postgame interview available →</button>':''}</section><section class="block"><header><h3>Last game</h3></header><div class="body">${lastGame()}</div></section></div>${q.teamId==null&&!c.retired?contractOffers(offers):''}`;
 }
 function contractOffers(offers){return offers.length?`<section class="block"><header><h3>Contract opportunities</h3></header><div class="body career-offers">${offers.map(o=>{const t=L().teams[o.teamId];return `<button class="career-offer" data-career-sign="${o.teamId}">${U.logo(t,42)}<h3>${esc(t.name)}</h3><p>${o.years} years · ${money(o.amount*1e6)} / year</p><p class="t2 sm">${o.role} · team ${t.w}–${t.l}</p><span class="caps">Consider this contract →</span></button>`;}).join('')}</div></section>`:'';}
 const TEND_LABELS={usage:'Shot involvement',three:'Three-point preference',mid:'Mid-range preference',drive:'Drive preference',post:'Post-up preference',passFirst:'Pass first',gamble:'Gamble for steals',crash:'Crash offensive glass',effort:'Effort',foulAggr:'Defensive aggression',drawFoul:'Seek contact'};
 function basketball(){const q=p(),c=L().career;return `<div class="cols c2"><section class="block"><header><h3>Prepare & develop</h3></header><div class="body">${actions('basketball')}<p class="t3 sm">${c.decisions} decisions remaining in the current week. Growth is gradual and has individual attribute caps.</p></div></section><section class="block"><header><h3>Your playing style</h3></header><form class="body stack" data-career-style>${Object.entries(TEND_LABELS).map(([key,label])=>`<label class="career-style"><span>${label}</span><input type="number" min="0" max="100" data-career-tend="${key}" value="${q.tend[key]}"></label>`).join('')}<button class="btn go" data-career-style-save>Save playing style</button><p class="t3 sm">Preferences are not skill ratings. Taking difficult shots or gambling with low ability can hurt your efficiency.</p></form></section></div><section class="block"><header><h3>Attributes & earned progress</h3></header><div class="body career-attributes">${HL.ATTRS.map(a=>`<div><span>${a.label}</span><b>${q.attrs[a.key]}</b><small>Cap ${q.caps[a.key]} · ${Math.round((c.progress[a.key]||0)*100)}% to next point</small></div>`).join('')}</div></section>`;}
 function people(){const c=L().career,q=p(),mates=Object.values(L().players).filter(x=>x.teamId===q.teamId&&x.id!==q.id&&!x.retired);return `<section class="block"><header><h3>Your circle</h3></header><div class="body career-circle">${Object.entries(c.people).map(([key,r])=>`<div><h3>${key}</h3>${meter('Like',r.like)}${meter('Respect',r.respect)}${meter('Trust',r.trust)}</div>`).join('')}</div></section><div class="draft-grid">${mates.map(m=>{const r=HL.World.relationship(L(),m.id);return `<button class="career-mate" data-career-support="${m.id}">${U.face(m,80)}<h3>${esc(m.name)}</h3><p class="t2">${m.pos} · ${m.ovr} OVR</p>${meter('Trust',r.trust)}<span class="caps">Offer support →</span></button>`;}).join('')}</div><p class="t3 sm">Coach trust affects your earned minutes. Teammates remember support as a specific relationship event.</p>`;}
 function life(){const c=L().career;return `<section class="career-game-stage"><div class="draft-kicker">YOUR MONEY · YOUR CHOICES</div><h2>${money(c.cash)}</h2><p>Gross earnings ${money(c.earnings)} · Withheld ${money(c.taxes)}. Salary arrives per regular-season team game, including paid DNPs; 35% combined tax/agent withholding is a simplified model.</p></section>${actions('life')}<section class="block"><header><h3>What you own</h3></header><div class="body">${c.possessions.length?c.possessions.map(x=>`<p>Car purchased in ${x.year} · ${money(x.price)}</p>`).join(''):'<p class="t3">Your possessions start with your first purchase.</p>'}</div></section><section class="block"><header><h3>Playing career</h3></header><div class="body"><p class="t2">Your life stays in this save when you step away. Return offers depend on age and available roster places.</p><button class="btn" data-career-retirement>${c.retired?'Seek a return':'Retire from the league'}</button></div></section>`;}
 function media(){const lg=L(),c=lg.career,q=p(),items=lg.news.filter(n=>n.playerIds?.includes(q.id)).slice(-20).reverse();return `${c.pendingPress?`<section class="career-game-stage"><div class="draft-kicker">POSTGAME INTERVIEW</div><h2>Your words travel.</h2><p>${c.pendingPress.pts} points in ${c.pendingPress.min.toFixed(1)} minutes. How do you handle the next step?</p><div class="career-actions"><button data-career-presser="humble"><strong>Stay humble</strong><span>“I still have a lot to learn. I will keep working.”</span></button><button data-career-presser="confident"><strong>Make a prediction</strong><span>“I will score at least 20 in our next game. Hold me to it.”</span></button><button data-career-presser="deflect"><strong>Keep it about the team</strong><span>“Tonight was about the team. I am keeping the next step private.”</span></button></div></section>`:''}${actions('media')}<section class="block"><header><h3>Coverage of your career</h3></header><div class="body stack">${items.map(n=>`<article class="career-story"><span class="caps">${HL.fmtDay(n.season,n.day)} · ${esc(n.type)}</span><h3>${esc(n.headline)}</h3><p>${esc(n.body||'')}</p>${(n.reactions||[]).slice(0,3).map(r=>`<blockquote>${esc(r.text)}<small>— ${esc(r.voice.outlet)}</small></blockquote>`).join('')}</article>`).join('')||'<p class="t3">Your public story begins when something happens.</p>'}</div></section>`;}
 function story(){const c=L().career;return `<section class="block"><header><h3>Season reports</h3></header><div class="body stack">${c.seasons.map(s=>`<article class="career-story"><h3>${s.season}–${String(s.season+1).slice(2)} · ${esc(s.team)} ${s.record}</h3><p>${s.stats.gp} games · ${s.stats.gp?(s.stats.pts/s.stats.gp).toFixed(1):'0.0'} PPG · ${s.stats.gp?(s.stats.min/s.stats.gp).toFixed(1):'0.0'} MPG · ${s.ovr} OVR</p><p>${s.awards.map(a=>esc(a.award)).join(' · ')||'No awards this season.'}</p>${s.series.map(x=>`<p>${esc(x.round)} · ${esc(L().teams[x.opponent].name)} · ${x.wins.join('–')} · ${x.won?'Advanced':'Eliminated'}</p>`).join('')||'<p class="t3">No playoff series played.</p>'}</article>`).join('')||'<p class="t3">Your first report arrives at the offseason.</p>'}</div></section><section class="block"><header><h3>Your storyline</h3></header><div class="body stack">${c.timeline.slice().reverse().map(e=>`<article class="career-story"><span class="caps">${HL.fmtDay(e.season,e.day,{year:true})} · ${e.public?'Public story':'Personal memory'}</span><p>${esc(e.text)}</p></article>`).join('')}</div></section>`;}
 function open(){if(HL.LiveGame?.active(L()))return HL.LiveGameUI.open();const lg=L(),c=lg.career,q=p(),t=lg.teams[q.teamId??lg.userTeamId];U.applyTeamTheme(t);U.setEra(HL.eraForSeason(lg.season));
  U.app().innerHTML=`<div class="frame career-frame"><div class="masthead"><div class="bar"><div class="wordmark" data-career-home>Hoops<i>Life</i></div><span class="caps">Player Career</span><span class="ml-auto">${HL.FX.soundToggle()}</span><button class="btn small" data-career-save>Save</button></div><nav class="subnav">${tabs.map(([id,name])=>`<button class="${id===tab?'on':''}" data-career-tab="${id}">${name}</button>`).join('')}</nav></div><main class="page"><div class="career-identity"><div><span class="caps">${esc(t.city)} ${esc(t.name)} · #${q.number} · ${q.pos} · Age ${q.age}</span><h1>${esc(q.name)}</h1><span class="t2">${c.retired?'Retired':c.role} · ${q.ovr} OVR · ${HL.fmtDay(lg.season,lg.day,{year:true})}</span></div><div class="career-meters">${meter('Energy',c.energy)}${meter('Happiness',c.happiness)}${meter('Reputation',c.reputation)}</div></div><div id="career-page">${{today,basketball,people,life,media,story}[tab]()}</div></main></div>`;bind();}
 function changed(){open();save();}
 function choiceSnapshot(){const c=L().career;return {'Energy':c.energy,'Happiness':c.happiness,'Reputation':c.reputation,'Cash':c.cash,'Coach trust':c.people.coach.trust,'Family trust':c.people.family.trust,'Ability':p().ovr,'Decisions':c.decisions};}
 function action(key,params={}){const before=choiceSnapshot(),r=C.act(L(),key,params);if(!r.ok){U.toast(esc(r.reason));return r;}const after=choiceSnapshot();r.feedback=Object.entries(after).filter(([k,v])=>v!==before[k]).map(([k,v])=>{const delta=v-before[k];return `<span class="${delta>0?'up':'down'}">${k} ${delta>0?'+':'−'}${k==='Cash'?money(Math.abs(delta)):Math.abs(delta)}</span>`;}).join('');if(key==='train')r.feedback+=`<span>${esc(HL.ATTRS.find(a=>a.key===params.focus).label)} · ${Math.round((L().career.progress[params.focus]||0)*100)}% to next point</span>`;changed();return r;}
 function dialog(key){const a=C.ACTIONS[key];U.closeSheet();const m=U.sheet(`<h3>${a.label}</h3>`,`<p>${a.desc}</p>${key==='train'?`<label>Focus<select data-action-focus>${HL.ATTRS.filter(a=>a.key!=='dur').map(a=>`<option value="${a.key}">${a.label}</option>`).join('')}</select></label>`:''}${key==='charity'?'<label>Donation · dollars<input type="number" data-action-amount value="500" min="1"></label>':''}${key==='car'?'<label>Price · dollars<input type="number" data-action-price value="15000" min="1000"></label>':''}<p class="t2">Cash ${money(L().career.cash)} · Energy ${L().career.energy} · ${L().career.decisions} decisions this week</p><button class="btn go" data-action-confirm>Make this choice</button><div role="status" data-action-result></div>`,{width:560});
  m.querySelector('[data-action-confirm]').onclick=()=>{const params={};if(key==='train')params.focus=m.querySelector('[data-action-focus]').value;if(key==='charity')params.amount=+m.querySelector('[data-action-amount]').value;if(key==='car')params.price=+m.querySelector('[data-action-price]').value;const r=action(key,params);m.querySelector('[data-action-result]').innerHTML=r.ok?`<strong class="career-choice-stamp">${L().career.timeline.at(-1)?.public?'The world takes notice':'A personal decision'}</strong><span>${esc(r.response)}</span><span class="career-choice-feedback">${r.feedback}</span>`:esc(r.reason);if(r.ok){m.querySelector('[data-action-confirm]').disabled=true;HL.FX.sfx.land();}};
 }
 function gameReveal(g){
  const lg=L(),q=p(),t=lg.teams[q.teamId],opp=lg.teams[g.opponent],coverage=lg.news.filter(n=>n.season===g.season&&n.day===g.day&&n.playerIds?.includes(q.id)&&['career.prediction','life.party.hangover_game'].includes(n.key)).slice(-2);
  const m=U.sheet('<h3>Final whistle</h3>',`<div class="career-game-reveal ${g.won?'won':'lost'}"><div class="draft-kicker">${HL.fmtDay(g.season,g.day)} · ${g.playoff?'PLAYOFFS':'REGULAR SEASON'}</div><div class="career-scoreboard">${U.logo(t,64)}<div><span>${esc(t.abbr)} / ${esc(opp.abbr)}</span><h2>${g.score}</h2><b>${g.won?'TEAM WIN':'TEAM LOSS'}</b></div>${U.logo(opp,64)}</div><h3>${esc(q.name)} · #${q.number}</h3><div class="career-statline">${[['pts','PTS'],['reb','REB'],['ast','AST']].map(([key,label])=>`<div><b data-career-reveal-stat="${key}">${g[key]}</b>${label}</div>`).join('')}<div><b>${g.min.toFixed(1)}</b>MIN</div></div><p>${g.min===0?'Did not play. Your team result is real; there is no personal performance to invent.':`${lg.career.role} · Coach trust ${lg.career.people.coach.trust} · Energy ${lg.career.energy}`}</p>${coverage.map(n=>`<article class="career-story"><h3>${esc(n.headline)}</h3><p>${esc(n.body)}</p>${(n.reactions||[]).slice(0,2).map(r=>`<blockquote>${esc(r.text)}<small>— ${esc(r.voice.outlet)}</small></blockquote>`).join('')}</article>`).join('')}<div class="row wrap">${lg.career.pendingPress?'<button class="btn go" data-career-reveal-press>Meet the press →</button>':''}<button class="btn ml-auto" data-career-reveal-close>Continue your story</button></div></div>`,{width:680});
  for(const key of ['pts','reb','ast'])HL.FX.countUp(m.querySelector(`[data-career-reveal-stat="${key}"]`),g[key],650);
  if(g.pts>=20&&g.min>0){HL.FX.burst(m.querySelector('.career-statline'),['#ff8a36','#ffe48a','#fff'],24);HL.FX.sfx.pop(2);}else HL.FX.sfx.land();
  m.querySelector('[data-career-reveal-close]').onclick=()=>U.closeSheet();m.querySelector('[data-career-reveal-press]')?.addEventListener('click',()=>{U.closeSheet();tab='media';open();});
 }
 function simulate(kind){if(busy)return;busy=true;const lg=L(),c=lg.career,last=c.gameLog.at(-1),start=lg.day;
  U.runWithProgress(kind==='season'?'Following the season':'Following the league',400,()=>{if(lg.phase==='offseason')return false;HL.League.simDay();if(kind==='next'&&!c.retired&&c.gameLog.at(-1)!==last)return false;if(kind==='week'||(kind==='next'&&c.retired)){if(lg.day-start>=7)return false;}},()=>{if(lg.phase==='offseason')C.offseason(lg);busy=false;changed();if(kind==='next'&&c.gameLog.at(-1)!==last)gameReveal(c.gameLog.at(-1));});
 }
 function bind(){const root=U.app();root.querySelector('[data-live-start]')?.addEventListener('click',()=>HL.LiveGameUI.start());HL.FX.bindSound(root);root.querySelectorAll('[data-career-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.careerTab;open();});root.querySelectorAll('[data-career-jump]').forEach(b=>b.onclick=()=>{tab=b.dataset.careerJump;open();});
  root.querySelector('[data-career-home]').onclick=async()=>{await save();HL.App.title();};root.querySelector('[data-career-save]').onclick=async()=>{await save();U.toast('Career saved.');};
  for(const[k,v]of[['next','next'],['week','week'],['season','season']])root.querySelector(`[data-career-${k}]`)?.addEventListener('click',()=>simulate(v));
  root.querySelectorAll('[data-career-action]').forEach(b=>b.onclick=()=>dialog(b.dataset.careerAction));root.querySelectorAll('[data-career-support]').forEach(b=>b.onclick=()=>{const r=action('teammate',{pid:+b.dataset.careerSupport});if(r.ok)U.toast(esc(r.response));});root.querySelectorAll('[data-career-presser]').forEach(b=>b.onclick=()=>action('presser',{tone:b.dataset.careerPresser}));
  root.querySelector('[data-career-style]')?.addEventListener('submit',e=>{e.preventDefault();const values={};root.querySelectorAll('[data-career-tend]').forEach(el=>values[el.dataset.careerTend]=+el.value);const r=C.setTendencies(L(),values);if(r.ok){save();U.toast('Playing style saved.');}else U.toast(esc(r.reason));});
  root.querySelector('[data-career-advance]')?.addEventListener('click',async()=>{if(busy)return;busy=true;try{const year=L().season+1;if(HL.League.usesRealHistory())await HL.History.load(String(year));const r=C.advance(L());if(!r.ok)U.toast(esc(r.reason));else{tab='today';changed();}}catch(e){U.toast(esc(e.message));}finally{busy=false;}});
  root.querySelectorAll('[data-career-sign]').forEach(b=>b.onclick=()=>{const id=+b.dataset.careerSign,o=C.offers(L()).find(o=>o.teamId===id);if(!o)return;const m=U.sheet('<h3>Contract decision</h3>',`<p>${esc(L().teams[id].name)} offer ${o.years} years at ${money(o.amount*1e6)} per year. ${o.role}.</p><button class="btn go" data-career-contract-confirm>Accept this contract</button>`,{width:520});m.querySelector('[data-career-contract-confirm]').onclick=()=>{const r=C.sign(L(),id);if(!r.ok)return U.toast(esc(r.reason));U.closeSheet();changed();};});
  root.querySelector('[data-career-retirement]')?.addEventListener('click',()=>{const returning=L().career.retired,m=U.sheet(`<h3>${returning?'Seek a return':'Retire from playing'}</h3>`,`<p>${returning?'Returning requires a real roster place and contract. Your age and earned skills remain.':'End the current playing contract and keep your life story. A later return needs a new offer.'}</p><button class="btn go" data-career-retire-confirm>${returning?'Seek offers':'Retire'}</button>`,{width:500});m.querySelector('[data-career-retire-confirm]').onclick=()=>{const r=returning?C.unretire(L()):C.retire(L());if(!r.ok)return U.toast(esc(r.reason));U.closeSheet();tab='today';changed();};});
 }
 return {setup,open};
})();
