// Actual possession decisions, with a focused broadcast stage and real people.
window.HL=window.HL||{};
HL.LiveGameUI=(function(){
 const U=HL.UI,G=HL.LiveGame,esc=U.esc,L=()=>HL.League.get();let busy=false;
 async function save(){await HL.Saves.save(L());}
 async function start(){if(busy)return;busy=true;try{const r=G.start(L());if(!r.ok)return U.toast(esc(r.reason));open();await save();}catch(e){U.toast(esc(e.message));}finally{busy=false;}}
 function controls(s){
  const t=(s.home.id===s.userTeamId?s.home:s.away),p=t.players.find(p=>p.id===s.pid),values={...(s.role==='player'?p.tend:HL.DEFAULT_STRATEGY()),...(s.role==='player'?{}:t.strategy)};
  for(const c of s.commands)Object.assign(values,c.values);
  const number=(key,label)=>`<label>${label}<input type="number" data-live-value="${key}" min="0" max="100" value="${values[key]}"></label>`;
  const select=(key,label,options)=>`<label>${label}<select data-live-value="${key}">${options.map(([v,name])=>`<option value="${v}" ${values[key]===v?'selected':''}>${name}</option>`).join('')}</select></label>`;
  return `<section class="block"><header><h3>${s.role==='player'?'Your intentions':'Your game plan'}</h3></header><form class="body live-choices" data-live-form>${s.role==='player'?number('usage','Shot involvement')+number('three','Three-point preference')+number('drive','Drive preference')+number('effort','Effort'):select('focus','Offensive focus',[['balanced','Balanced'],['inside','Attack inside'],['perimeter','Find threes'],['star','Lean on our star']])+select('defense','Defensive coverage',[['man','Man'],['switch','Switch'],['drop','Drop'],['zone','Zone'],['press','Press']])+number('pace','Pace')+number('crash','Crash offensive glass')}<button class="btn go" data-live-decide ${s.role==='coach'?'data-live-coach':''}>Commit this approach</button><p class="t3 sm">${s.role==='player'?'These are your intentions for this game. Your coach still decides when you play; your ability and fitness still matter.':'Coverage, pace, shot selection and rebounding change actual possessions. Illegal zone coverage falls back to man under the current rules.'}</p><p role="status" data-live-response></p></form></section>`;
 }
 function lineup(s,v,side){const T=s[side],b=v[side].box,list=v.lineups[T.id]||[];return `<section class="block"><header><h3>${esc(T.abbr)} · On the floor</h3></header><div class="body live-lineup">${list.map(x=>{const p=T.players.find(p=>p.id===x.pid),line=b[p.id]||{};return `<div class="live-player">${U.face(p,54,L().teams[T.id])}<div><strong>${esc(p.name)}</strong><span>${line.pts||0} PTS · ${x.fouls} fouls · ${Math.round(x.energy*100)}% energy</span></div></div>`;}).join('')||'<p class="t3">The opening lineup enters at tipoff.</p>'}</div></section>`;}
 function open(){const lg=L(),s=lg.liveGame;if(!s)return back();const v=G.view(lg),home=lg.teams[s.home.id],away=lg.teams[s.away.id];U.applyTeamTheme(lg.teams[s.userTeamId]);U.setEra(HL.eraForSeason(lg.season));
  U.app().innerHTML=`<div class="frame live-frame"><div class="masthead"><div class="bar"><div class="wordmark">Hoops<i>Life</i></div><span class="caps">Live Game</span><span class="ml-auto">${HL.FX.soundToggle()}</span><button class="btn small" data-live-save>Save & exit</button></div></div><main class="page"><section class="live-score-stage"><div class="draft-kicker">${HL.fmtDay(s.season,s.day)} · ${s.committed?'FINAL':v.period>4?'OVERTIME '+(v.period-4):v.period?'QUARTER '+v.period:'TIPOFF'}</div><div class="live-scoreboard"><div>${U.logo(home,80)}<h3>${esc(home.name)}</h3><b data-live-score="home">${v.home.score}</b></div><div class="live-clock">${s.committed?'FINAL':v.clock}<span>${s.role==='player'?'Your player. Your approach.':'Your team. Your calls.'}</span></div><div>${U.logo(away,80)}<h3>${esc(away.name)}</h3><b data-live-score="away">${v.away.score}</b></div></div><div class="row wrap live-buttons"><button class="btn" data-live-box>Box score</button>${s.committed?'<button class="btn go" data-live-back>Return to your story →</button>':'<button class="btn go" data-live-step="1">Next possession →</button><button class="btn" data-live-step="12">Run 12 possessions</button><button class="btn quiet" data-live-finish>Auto-finish this game</button>'}</div></section><div class="live-layout"><div class="stack">${s.committed?`<section class="block"><header><h3>The world responds</h3></header><div class="body">${lg.news.filter(n=>n.key==='live.game'&&n.day===s.day&&n.season===s.season).map(n=>`<h3>${esc(n.headline)}</h3><p>${esc(n.body)}</p>`).join('')||'<p>Your actual result is now part of the standings, box score and season story.</p>'}</div></section>`:controls(s)}<section class="block"><header><h3>Live call</h3></header><div class="body live-pbp" aria-live="polite">${(v.pbp||[]).slice(-10).reverse().map(x=>`<p><span>Q${x.q} · ${esc(x.t)}</span>${esc(x.txt)}</p>`).join('')||'<p class="t3">Choose your approach, then let the first possession unfold.</p>'}</div></section></div><div class="stack">${lineup(s,v,'home')}${lineup(s,v,'away')}<p class="t3 sm">This first Live Game milestone covers regular-season decisions. Substitutions, timeouts, challenges and postseason decision play are still in development.</p></div></div></main></div>`;bind();}
 function back(){(L().career?HL.CareerUI:HL.Franchise).open();}
 function boxScore(){const s=L().liveGame,v=G.view(L());U.sheet('<h3>Actual box score</h3>',['home','away'].map(side=>`<section class="block"><header><h3>${esc(s[side].abbr)}</h3></header><div class="table-scroll"><table><thead><tr><th class="l">Player</th><th>MIN</th><th>PTS</th><th>REB</th><th>AST</th><th>FG</th><th>TOV</th><th>PF</th></tr></thead><tbody>${s[side].players.map(p=>{const b=v[side].box[p.id]||{};return `<tr><td class="l">${esc(p.name)}${b.gp?'':' · DNP'}</td><td>${(b.min||0).toFixed(1)}</td><td>${b.pts||0}</td><td>${(b.orb||0)+(b.drb||0)}</td><td>${b.ast||0}</td><td>${b.fgm||0}/${b.fga||0}</td><td>${b.tov||0}</td><td>${b.pf||0}</td></tr>`;}).join('')}</tbody></table></div></section>`).join(''),{width:880});}
 function bind(){const root=U.app();root.querySelector('[data-live-box]').onclick=boxScore;HL.FX.bindSound(root);root.querySelector('[data-live-save]').onclick=async()=>{await save();HL.App.title();};root.querySelector('[data-live-back]')?.addEventListener('click',back);
  root.querySelector('[data-live-form]')?.addEventListener('submit',async e=>{e.preventDefault();const values={};root.querySelectorAll('[data-live-value]').forEach(x=>values[x.dataset.liveValue]=x.type==='number'?(x.value.trim()===''?NaN:+x.value):x.value);const r=G.decide(L(),values);if(r.ok){await save();HL.FX.sfx.land();}root.querySelector('[data-live-response]').textContent=r.ok?'Your approach is set for the next possession.':r.reason;});
  root.querySelectorAll('[data-live-step]').forEach(b=>b.onclick=async()=>{if(busy)return;busy=true;try{const r=G.step(L(),+b.dataset.liveStep);if(!r.ok)U.toast(esc(r.reason));else{open();await save();HL.FX.sfx.tick();}}finally{busy=false;}});
  root.querySelector('[data-live-finish]')?.addEventListener('click',()=>{if(busy)return;busy=true;U.runWithProgress('Playing out your decisions',100,()=>{const r=G.step(L(),12);if(!r.ok||r.finished)return false;},()=>{busy=false;open();save();if(L().liveGame.committed){HL.FX.countUp(U.app().querySelector('[data-live-score="home"]'),L().liveGame.result.home.score);HL.FX.countUp(U.app().querySelector('[data-live-score="away"]'),L().liveGame.result.away.score);}});});
 }
 return {start,open};
})();
