// Actual possession decisions, with a focused broadcast stage and real people.
window.HL=window.HL||{};
HL.LiveGameUI=(function(){
 const U=HL.UI,G=HL.LiveGame,esc=U.esc,L=()=>HL.League.get();let busy=false,panel='approach',receipt='';
 async function save(){await HL.Saves.save(L());}
 async function start(){if(busy)return;busy=true;try{const r=G.start(L());if(!r.ok)return U.toast(esc(r.reason));open();await save();}catch(e){U.toast(esc(e.message));}finally{busy=false;}}
 function controls(s,v){
  const t=(s.home.id===s.userTeamId?s.home:s.away),opponent=t===s.home?s.away:s.home,p=t.players.find(p=>p.id===s.pid),values={...(s.role==='player'?p.tend:HL.DEFAULT_STRATEGY()),...(s.role==='player'?{}:t.strategy)};
  for(const c of s.commands)if(c.kind!=='action')Object.assign(values,c.values);
  const number=(key,label,help)=>`<label>${label}<input type="number" data-live-value="${key}" min="0" max="100" value="${values[key]??50}"><small>${help||'0 = seldom · 100 = often'}</small></label>`;
  const select=(key,label,options)=>`<label>${label}<select data-live-value="${key}">${options.map(([v,name])=>`<option value="${v}" ${values[key]===v?'selected':''}>${name}</option>`).join('')}</select></label>`;
  const tabs=s.role==='player'?[['approach','My approach'],['playbook','Call a play']]:[['approach','Game plan'],['bench','Bench'],['playbook','Playbook'],['matchups','Matchups'],['talk','Team talk']];
  if(!tabs.some(([id])=>id===panel))panel='approach';
  const ids=v.lineups[t.id]?.map(x=>x.pid)||[],floor=t.players.filter(p=>ids.includes(p.id)),state=v.tactics?.[t.id]||{},roster=v.roster?.[t.id]||[],side=t===s.home?v.home:v.away;
  const available=t.players.filter(p=>!v.out.includes(p.id)&&(!p.injury||p.injury.games<=0));
  const pick=(players,selected)=>players.map(p=>`<option value="${p.id}" ${p.id===selected?'selected':''}>${esc(p.name)} · ${p.pos}</option>`).join('');
  let body='';
  if(panel==='approach')body=`<form class="live-choices" data-live-form>${s.role==='player'?`<fieldset><legend>Get your shot</legend>${number('usage','Shot involvement','Ask for more touches; the coach still sets your minutes.')+number('three','Three-point preference')+number('mid','Mid-range preference')+number('drive','Attack the basket')+number('post','Post-up preference')+number('drawFoul','Seek contact','More free-throw chances; your finishing ability still matters.')}</fieldset><fieldset><legend>Help the team</legend>${number('passFirst','Look to pass','Higher values reduce your own usage and favor a passing role.')+number('gamble','Gamble for steals','More disruption, with defensive risks.')+number('foulAggr','Physical defense','Aggressive defense increases foul exposure.')+number('crash','Crash the glass','Prioritize rebounds over getting back.')+number('effort','Effort','Higher effort drains energy faster.')}</fieldset>`:select('focus','Offensive focus',[['balanced','Balanced'],['inside','Attack inside'],['perimeter','Find threes'],['star','Lean on our star'],['motion','Motion and ball movement']])+select('defense','Defensive coverage',[['man','Man'],['switch','Switch'],['drop','Drop'],['zone','Zone'],['press','Press']])+number('pace','Pace','Run faster or work longer for a shot.')+number('crash','Crash offensive glass','Send more players after the offensive rebound.')}<button class="btn go" data-live-decide ${s.role==='coach'?'data-live-coach':''}>Commit this approach</button><p class="t3 sm">${s.role==='player'?'Intentions change your play. Ability, fitness and the coach’s rotation still decide the opportunity.':'Coverage, pace, shot selection and rebounding change actual possessions. Illegal zone coverage falls back to man under the current rules.'}</p><p role="status" data-live-response></p></form>`;
  if(panel==='bench')body=`<p>${state.manual?'Your chosen five stays together until you change it or someone becomes unavailable.':'The coach’s automatic rotation is active.'} Any positions can share the floor; guard skills and interior defense still matter.</p><form data-live-lineup-form><div class="live-bench-roster">${t.players.map(p=>{const r=roster.find(x=>x.pid===p.id),b=side.box[p.id]||{},unavailable=!available.includes(p);return `<label class="live-roster-choice ${ids.includes(p.id)?'on-floor':''}"><input type="checkbox" data-live-roster-pid="${p.id}" ${ids.includes(p.id)?'checked':''} ${unavailable?'disabled':''}>${U.face(p,48,L().teams[t.id])}<span><strong>${esc(p.name)}</strong><small>${p.pos} · ${p.ovr} OVR · ${(b.min||0).toFixed(1)} MIN · ${b.pts||0} PTS</small><small>${unavailable?'Unavailable':Math.round((r?.energy??1)*100)+'% energy'} · ${r?.fouls||0} fouls</small></span></label>`;}).join('')}</div><div class="row wrap"><button class="btn go" data-live-lineup>Put this five on the floor</button><button class="btn" type="button" data-live-auto>Use automatic rotations</button></div><p class="t3 sm">Select exactly five. Injuries and foul-outs trigger emergency substitutions.</p></form>`;
  if(panel==='playbook'){
    const ownFloor=s.role==='player'?floor.filter(p=>p.id===s.pid):floor;
    body=`<p>Draw up the next possession your team has. A call favors the action; defense can still deny it, force a turnover or contest the shot.</p>${!floor.length?'<p class="t3">Tip off to see the actual opening five.</p>':s.role==='player'&&!ownFloor.length?'<p class="live-bench-notice">You are on the bench. Stay ready; your coach decides when you enter.</p>':''}<form class="live-choices" data-live-play-form><label>Action<select data-live-play-type>${Object.entries(HL.GAME_PLAYS).map(([id,x])=>`<option value="${id}">${esc(x.label)}</option>`).join('')}</select></label><label>${s.role==='player'?'Your involvement':'Primary player'}<select data-live-play-pid ${s.role==='player'?'disabled':''}>${pick(ownFloor,s.pid)}</select></label><label data-live-partner-label>Partner / receiver<select data-live-play-partner>${pick(floor,floor.at(-1)?.id)}</select></label><p class="t3 sm" data-live-play-help>${esc(HL.GAME_PLAYS.pickRoll.desc)}</p><button class="btn go" data-live-play-send ${!ownFloor.length?'disabled':''}>Call this play</button></form>${state.pendingPlay?`<div class="live-call-receipt">Queued: ${esc(HL.GAME_PLAYS[state.pendingPlay.play].label)} · ${esc(t.players.find(p=>p.id===state.pendingPlay.pid)?.name||'')}.</div>`:''}`;
  }
  if(panel==='matchups')body=`<p>Choose who takes the assignment. Pressure has a cost: tight coverage exposes drives and fouls; sagging gives up jumpers; denial invites cuts; traps can free another shooter.</p><form class="live-choices" data-live-matchup-form><label>Your defender<select data-live-defender>${pick(floor)}</select></label><label>Opponent<select data-live-target>${pick(opponent.players.filter(p=>!v.out.includes(p.id)))}</select></label><label>Pressure<select data-live-pressure><option value="tight">Tight — contest jumpers</option><option value="sag">Sag — protect the paint</option><option value="deny">Deny — reduce touches</option><option value="trap">Trap — force the ball out</option></select></label><button class="btn go" data-live-matchup-send ${!floor.length?'disabled':''}>Set the assignment</button><button type="button" class="btn" data-live-matchup-clear>Return to automatic matchups</button></form>${state.matchup?`<p class="live-call-receipt">${esc(t.players.find(p=>p.id===state.matchup.pid)?.name||'')} → ${esc(opponent.players.find(p=>p.id===state.matchup.targetId)?.name||'')} · ${esc(state.matchup.pressure)}. Applies while both are on the floor.</p>`:''}`;
  if(panel==='talk')body=`<p>Say it in your own words. Choose how you mean it: a challenge can motivate a driven group or frustrate proud players. The response lasts six offensive possessions; another talk replaces it.</p><form class="live-choices" data-live-talk-form><label>How you address them<select data-live-talk-intent><option value="encourage">Encourage</option><option value="challenge">Challenge</option><option value="calm">Calm things down</option><option value="accountability">Demand accountability</option><option value="reassure">Reassure</option><option value="focus">Refocus</option></select></label><label class="live-talk-words">Your words<textarea data-live-talk-words maxlength="2000" rows="4" placeholder="Tell them what you see and what you need…"></textarea></label><button class="btn go" data-live-talk-send>Speak to the team</button></form>${state.huddle?`<blockquote class="live-talk-quote">“${esc(state.huddle.text)}”<small>${esc(state.huddle.intent)} · ${state.huddle.remaining} possessions remain</small></blockquote><div class="live-huddle-replies">${(state.huddle.responses||[]).map(r=>`<div class="live-player">${U.face(t.players.find(p=>p.id===r.pid),36,L().teams[t.id])}<div><strong>${esc(r.name)}</strong><span>${esc(r.text)}</span></div></div>`).join('')}</div>`:''}`;
  return `<section class="block live-sideline"><header><h3>${s.role==='player'?'Your decisions':'The sideline'}</h3>${s.role==='coach'?`<button class="btn small" data-live-timeout ${v.period===0?'disabled':''}>Timeout · ${state.timeouts??(s.season>=2017?7:6)} left</button>`:''}</header><nav class="live-decision-tabs">${tabs.map(([id,label])=>`<button data-live-tab="${id}" class="${id===panel?'active':''}">${label}</button>`).join('')}</nav><div class="body">${body}<p class="live-call-receipt" role="status" data-live-receipt>${esc(receipt)}</p></div></section>`;
 }
 function lineup(s,v,side){const T=s[side],b=v[side].box,list=v.lineups[T.id]||[];return `<section class="block"><header><h3>${esc(T.abbr)} · On the floor</h3></header><div class="body live-lineup">${list.map(x=>{const p=T.players.find(p=>p.id===x.pid),line=b[p.id]||{};return `<div class="live-player">${U.face(p,54,L().teams[T.id])}<div><strong>${esc(p.name)}</strong><span>${line.pts||0} PTS · ${x.fouls} fouls · ${Math.round(x.energy*100)}% energy</span></div></div>`;}).join('')||'<p class="t3">The opening lineup enters at tipoff.</p>'}</div></section>`;}
 function open(){const lg=L(),s=lg.liveGame;if(!s)return back();const v=G.view(lg),home=lg.teams[s.home.id],away=lg.teams[s.away.id];U.applyTeamTheme(lg.teams[s.userTeamId]);U.setEra(HL.eraForSeason(lg.season));
  U.app().innerHTML=`<div class="frame live-frame"><div class="masthead"><div class="bar"><div class="wordmark">Hoops<i>Life</i></div><span class="caps">Live Game</span><span class="ml-auto">${HL.FX.soundToggle()}</span><button class="btn small" data-live-save>Save & exit</button></div></div><main class="page"><section class="live-score-stage"><div class="draft-kicker">${HL.fmtDay(s.season,s.day)} · ${s.committed?'FINAL':v.period>4?'OVERTIME '+(v.period-4):v.period?'QUARTER '+v.period:'TIPOFF'}</div><div class="live-scoreboard"><div>${U.logo(home,80)}<h3>${esc(home.name)}</h3><b data-live-score="home">${v.home.score}</b></div><div class="live-clock">${s.committed?'FINAL':v.clock}<span>${!s.committed&&v.possessionTeamId!=null?'Ball: '+esc(lg.teams[v.possessionTeamId]?.abbr||'')+' · ':''}${s.role==='player'?'Your player. Your approach.':'Your team. Your calls.'}</span></div><div>${U.logo(away,80)}<h3>${esc(away.name)}</h3><b data-live-score="away">${v.away.score}</b></div></div><div class="row wrap live-buttons"><button class="btn" data-live-box>Box score</button>${s.committed?'<button class="btn go" data-live-back>Return to your story →</button>':'<button class="btn go" data-live-step="1">Next possession →</button><button class="btn" data-live-step="12">Run 12 possessions</button><button class="btn quiet" data-live-finish>Auto-finish this game</button>'}</div></section><div class="live-layout"><div class="stack">${s.committed?`<section class="block"><header><h3>The world responds</h3></header><div class="body">${lg.news.filter(n=>n.key==='live.game'&&n.day===s.day&&n.season===s.season).map(n=>`<h3>${esc(n.headline)}</h3><p>${esc(n.body)}</p>${(n.reactions||[]).map(r=>`<blockquote class="live-talk-quote">${esc(r.text)}<small>${esc(r.voice?.outlet||'')}</small></blockquote>`).join('')}`).join('')||'<p>Your actual result is now part of the standings, box score and season story.</p>'}</div></section>`:controls(s,v)}<section class="block"><header><h3>Live call</h3></header><div class="body live-pbp" aria-live="polite">${(v.pbp||[]).slice(-10).reverse().map(x=>`<p><span>Q${x.q} · ${esc(x.t)}</span>${esc(x.txt)}</p>`).join('')||'<p class="t3">Choose your approach, then let the first possession unfold.</p>'}</div></section></div><div class="stack">${lineup(s,v,'home')}${lineup(s,v,'away')}<p class="t3 sm">Regular-season decisions resolve between simulated possessions. Modern timeout limits: at most four in Q4 and two in its last three minutes. Earlier eras count full timeouts only; short timeouts are not modeled. Challenges and postseason live play remain in development.</p></div></div></main></div>`;bind();}
 function back(){(L().career?HL.CareerUI:HL.Franchise).open();}
 function boxScore(){const s=L().liveGame,v=G.view(L());U.sheet('<h3>Actual box score</h3>',['home','away'].map(side=>`<section class="block"><header><h3>${esc(s[side].abbr)}</h3></header><div class="table-scroll"><table><thead><tr><th class="l">Player</th><th>MIN</th><th>PTS</th><th>REB</th><th>AST</th><th>FG</th><th>TOV</th><th>PF</th></tr></thead><tbody>${s[side].players.map(p=>{const b=v[side].box[p.id]||{};return `<tr><td class="l">${esc(p.name)}${b.gp?'':' · DNP'}</td><td>${(b.min||0).toFixed(1)}</td><td>${b.pts||0}</td><td>${(b.orb||0)+(b.drb||0)}</td><td>${b.ast||0}</td><td>${b.fgm||0}/${b.fga||0}</td><td>${b.tov||0}</td><td>${b.pf||0}</td></tr>`;}).join('')}</tbody></table></div></section>`).join(''),{width:880});}
 function bind(){const root=U.app();root.querySelector('[data-live-box]').onclick=boxScore;HL.FX.bindSound(root);root.querySelector('[data-live-save]').onclick=async()=>{await save();HL.App.title();};root.querySelector('[data-live-back]')?.addEventListener('click',back);
  root.querySelectorAll('[data-live-tab]').forEach(b=>b.onclick=()=>{panel=b.dataset.liveTab;open();});
  async function command(kind,values={}){if(busy)return;busy=true;try{const r=G.act(L(),kind,values);receipt=r.ok?r.response:r.reason;if(r.ok){await save();HL.FX.sfx.land();}open();}finally{busy=false;}}
  root.querySelector('[data-live-timeout]')?.addEventListener('click',()=>command('timeout'));
  root.querySelector('[data-live-auto]')?.addEventListener('click',()=>command('autoRotation'));
  root.querySelector('[data-live-lineup-form]')?.addEventListener('submit',e=>{e.preventDefault();command('lineup',{pids:[...root.querySelectorAll('[data-live-roster-pid]:checked')].map(x=>+x.dataset.liveRosterPid)});});
  const playType=root.querySelector('[data-live-play-type]'),primary=root.querySelector('[data-live-play-pid]'),partner=root.querySelector('[data-live-play-partner]');
  function adjustPlay(){if(!playType)return;const spec=HL.GAME_PLAYS[playType.value];root.querySelector('[data-live-partner-label]').hidden=!spec.partner;root.querySelector('[data-live-play-help]').textContent=spec.desc;for(const o of partner.options)o.disabled=o.value===primary.value;if(partner.value===primary.value)partner.value=[...partner.options].find(o=>!o.disabled)?.value||'';}
  playType?.addEventListener('change',adjustPlay);primary?.addEventListener('change',adjustPlay);adjustPlay();
  root.querySelector('[data-live-play-form]')?.addEventListener('submit',e=>{e.preventDefault();const v={play:playType.value,pid:+primary.value};if(HL.GAME_PLAYS[v.play].partner)v.partnerId=+partner.value;command('play',v);});
  root.querySelector('[data-live-matchup-form]')?.addEventListener('submit',e=>{e.preventDefault();command('matchup',{pid:+root.querySelector('[data-live-defender]').value,targetId:+root.querySelector('[data-live-target]').value,pressure:root.querySelector('[data-live-pressure]').value});});
  root.querySelector('[data-live-matchup-clear]')?.addEventListener('click',()=>command('clearMatchup'));
  root.querySelector('[data-live-talk-form]')?.addEventListener('submit',e=>{e.preventDefault();command('huddle',{intent:root.querySelector('[data-live-talk-intent]').value,text:root.querySelector('[data-live-talk-words]').value});});
  root.querySelector('[data-live-form]')?.addEventListener('submit',async e=>{e.preventDefault();const values={};root.querySelectorAll('[data-live-value]').forEach(x=>values[x.dataset.liveValue]=x.type==='number'?(x.value.trim()===''?NaN:+x.value):x.value);const r=G.decide(L(),values);if(r.ok){await save();HL.FX.sfx.land();}root.querySelector('[data-live-response]').textContent=r.ok?'Your approach is set for the next possession.':r.reason;});
  root.querySelectorAll('[data-live-step]').forEach(b=>b.onclick=async()=>{if(busy)return;busy=true;try{const r=G.step(L(),+b.dataset.liveStep);if(!r.ok)U.toast(esc(r.reason));else{open();await save();HL.FX.sfx.tick();}}finally{busy=false;}});
  root.querySelector('[data-live-finish]')?.addEventListener('click',()=>{if(busy)return;busy=true;U.runWithProgress('Playing out your decisions',100,()=>{const r=G.step(L(),12);if(!r.ok||r.finished)return false;},()=>{busy=false;open();save();if(L().liveGame.committed){HL.FX.countUp(U.app().querySelector('[data-live-score="home"]'),L().liveGame.result.home.score);HL.FX.countUp(U.app().querySelector('[data-live-score="away"]'),L().liveGame.result.away.score);}});});
 }
 return {start,open};
})();
